<a href="https://colab.research.google.com/github/Anshika91/Deep_Learning/blob/main/functional_model_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

neural network architecture using functional model


In [41]:
#functional Model
from keras.layers import concatenate
from keras.layers import *
from keras.models import Model
from keras.layers import Dense
import tensorflow as tf
tf.random.set_seed(34)
x = Input(shape=2)
h1_1 = Dense(units=2,activation='relu')(x)
h1_2 = Dense(units=2,activation='relu')(x)
C = concatenate([h1_1,h1_2])
h2 = Dense(units=2,activation='relu')(C)
o = Dense(units=1,activation='sigmoid')(h2)
functional_model = Model(x,o)
functional_model.summary()

Model: "model_11"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_12 (InputLayer)          [(None, 2)]          0           []                               
                                                                                                  
 dense_44 (Dense)               (None, 2)            6           ['input_12[0][0]']               
                                                                                                  
 dense_45 (Dense)               (None, 2)            6           ['input_12[0][0]']               
                                                                                                  
 concatenate_11 (Concatenate)   (None, 4)            0           ['dense_44[0][0]',               
                                                                  'dense_45[0][0]']        

In [42]:
import numpy as np
ip=np.array([[0,0],[0,1],[1,0],[1,1]])
op=np.array([[0],[1],[1],[1]])

In [43]:
functional_model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [44]:
history=functional_model.fit(ip,op,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 465ms/step - loss: 0.2494 - accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 0.2491 - accuracy: 0.7500
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 0.2485 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 12ms/step - loss: 0.2482 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 0.2477 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 0.2472 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 0.2468 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.2463 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 0.2460 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 0.2455 - accuracy: 1.0000


In [45]:
#evaluate the network
loss,accuracy=functional_model.evaluate(ip,op)
print(loss)
print(accuracy)

1/1 [==============================] - 0s 139ms/step - loss: 0.2451 - accuracy: 1.0000
0.24513067305088043
1.0


In [49]:
#make predictions
prediction=functional_model.predict(ip)
prediction=(functional_model.predict(ip)>0.5).astype(int)
prediction

1/1 [==============================] - 0s 22ms/step


array([[0],
       [1],
       [1],
       [1]])

In [47]:
print(prediction)

[[0]
 [1]
 [1]
 [1]]


In [51]:
functional_model.layers

In [60]:
hidden1 = functional_model.layers[1]
output = functional_model.layers[-1]
weights,biasis = hidden1.get_weights()
print('weights:',weights)
print('bias:',biasis)

weights: [[-0.06775985 -0.5860491 ]
 [ 1.1021895   0.46462747]]
bias: [-4.7680642e-04  3.3294389e-05]


In [58]:
#check what is waeights and bias
output = functional_model.layers[-1]
weights,biasis = hidden1.get_weights()


In [57]:
print('weights:',weights)

weights: [[-0.06775985 -0.5860491 ]
 [ 1.1021895   0.46462747]]


In [56]:
print('bias:',biasis)

[-4.7680642e-04  3.3294389e-05]


In [59]:
functional_model.get_weights()

[array([[-0.06775985, -0.5860491 ],
        [ 1.1021895 ,  0.46462747]], dtype=float32),
 array([-4.7680642e-04,  3.3294389e-05], dtype=float32),
 array([[-1.0973021 ,  1.1864463 ],
        [ 0.02295705,  1.0725151 ]], dtype=float32),
 array([3.0703057e-05, 6.9284003e-04], dtype=float32),
 array([[ 0.5355368 ,  0.854027  ],
        [ 0.2573739 ,  0.78471994],
        [-0.46672544,  0.6611636 ],
        [ 0.8246855 ,  1.011863  ]], dtype=float32),
 array([0.00130396, 0.0008273 ], dtype=float32),
 array([[-0.29235289],
        [ 1.4237397 ]], dtype=float32),
 array([-0.00565884], dtype=float32)]