<a href="https://colab.research.google.com/github/Anshika91/Deep_Learning/blob/main/Tensorflow3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ragged Array. and Ragged Tensors


In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11]])

<ipython-input-3-e9f03e10e52e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11]])


In [ ]:
x

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]), list([10, 11])],
      dtype=object)

In [ ]:
# Ragged array A special kind of array that represents a list of arrays of differenet siz., it is a tensor with one or more ragged dimensions.
import tensorflow as tf
#tf.constant([1.,2,3],[4.,5,6.,7.]) # Not able 
r1=tf.ragged.constant([[65,66],[],[67]])

In [ ]:
r2=tf.ragged.constant([[67,97,102,233],[67,111,102,102,101,101],[99,97,102,102,232],[21654,21857]])

In [ ]:
r3=tf.concat([r1,r2],axis=0)

In [ ]:
r3.shape  # r3 shape is tensor shape.

TensorShape([7, None])

In [ ]:
r4=tf.ragged.constant([[1,2,3],[4]])

In [ ]:
r5=tf.ragged.constant([[5,6],[7,8,3]])

In [ ]:
tf.concat([r4,r5],axis=0)

<tf.RaggedTensor [[1, 2, 3], [4], [5, 6], [7, 8, 3]]>

In [ ]:
tf.concat([r4,r5],axis=1)

<tf.RaggedTensor [[1, 2, 3, 5, 6], [4, 7, 8, 3]]>

In [ ]:
r6=tf.ragged.constant([[5,6],[7,8,9,10]])

In [ ]:
tf.concat([r4,r6],axis=0)

<tf.RaggedTensor [[1, 2, 3], [4], [5, 6], [7, 8, 9, 10]]>

In [ ]:
tf.concat([r4,r6],axis=1)

<tf.RaggedTensor [[1, 2, 3, 5, 6],
 [4, 7, 8, 9, 10]]>

In [ ]:
r7=tf.ragged.constant([[1,2],[3,4],[5]])
r8=tf.ragged.constant([[7],[],[9,10,11]])

In [ ]:
tf.concat([r7,r8],axis=0)

<tf.RaggedTensor [[1, 2], [3, 4], [5], [7], [], [9, 10, 11]]>

In [ ]:
tf.concat([r7,r8],axis=1)

<tf.RaggedTensor [[1, 2, 7], [3, 4], [5, 9, 10, 11]]>

In [ ]:
r8=tf.ragged.constant([[7],[],[9,10,11],[12,13]])

In [ ]:
r8

<tf.RaggedTensor [[7], [], [9, 10, 11], [12, 13]]>

In [ ]:
r8.to_tensor()

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  0,  0],
       [ 0,  0,  0],
       [ 9, 10, 11],
       [12, 13,  0]], dtype=int32)>

In [ ]:
r8.to_tensor(default_value=5)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  5,  5],
       [ 5,  5,  5],
       [ 9, 10, 11],
       [12, 13,  5]], dtype=int32)>

In [ ]:
a=tf.constant([[1,5,9]])
b=tf.constant([[5,6,9,11]])
u=tf.sets.union(a,b)

In [ ]:
u

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]], shape=(5, 2), dtype=int64), values=tf.Tensor([ 1  5  6  9 11], shape=(5,), dtype=int32), dense_shape=tf.Tensor([1 5], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(u)

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 1,  5,  6,  9, 11]], dtype=int32)>

In [ ]:
q=tf.queue.FIFOQueue(3,[tf.int32,tf.string],shapes=[(),()])

In [ ]:
q.enqueue([10,b"windy"])
q.enqueue([15,b"sunny"])
q.size()

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
q.dequeue()

[<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'windy'>]

Multiple records at once using enqueue_many() and dequeue_many()

In [ ]:
q.enqueue_many([[13,16],[b'cloudy',b'rainy']])
q.dequeue_many(3)

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 13, 16], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=string, numpy=array([b'sunny', b'cloudy', b'rainy'], dtype=object)>]

Graphical mode and eager mode
Customizing models

In [ ]:
#My_loss_fn
def my_loss_fn(y_true,y_pred):
  error=y_true-y_pred
  is_small_error=tf.abs(error)<1
  squared_loss=tf.square(error)/2
  linear_loss=tf.abs(error)-0.5
  return tf.where(is_small_error,squared_loss,linear_loss)

In [ ]:
#CNN
